fix(chart/kyverno): handle multiple extraArgs in init container (#5846)
The lack of the nindent was causing rendering to fail:

```
Error: YAML parse error on kyverno/templates/deployment.yaml: error converting YAML to JSON: yaml: line 75: did not find expected key
helm.go:81: [debug] error converting YAML to JSON: yaml: line 75: did not find expected key
YAML parse error on kyverno/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
```

Reproducible by having the following values:

```
initContainer:
  extraArgs:
    - "--loggingFormat=json"
    - "-v=-1"
```

Signed-off-by: Adrien Fillon <adrien.fillon@manomano.com>

Signed-off-by: Adrien Fillon <adrien.fillon@manomano.com>